namespace SpriteKind {
    export const Text = SpriteKind.create()
}
let Me = sprites.create(img`
    ........................
    .....ffff...............
    ...fff22fff.............
    ..fff2222fff............
    .fffeeeeeefff...........
    .ffe222222eef...........
    .fe2ffffff2ef...........
    .ffffeeeeffff...........
    ffefbf44fbfeff..........
    fee41fddf14eef..........
    .ffffdddddeef...........
    fddddf444eef............
    fbbbbf2222f4e...........
    fbbbbf2222fd4...........
    .fccf45544f44...........
    ..ffffffff..............
    ....ff..ff..............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
controller.moveSprite(Me)
scene.cameraFollowSprite(Me)
let PanelImg = image.create(scene.screenWidth(), 16)
let InfoPanel = sprites.create(PanelImg, SpriteKind.Text)
let textSprite = textsprite.create("-")
game.onUpdate(function () {
    InfoPanel.setPosition(scene.cameraProperty(CameraProperty.X) + 0, scene.cameraProperty(CameraProperty.Bottom) - 8)
    for (let index = 0; index <= scene.screenWidth(); index++) {
        PanelImg.drawTransparentImage(img`
            2 
            `, index, 0)
    }
    textSprite.setText("" + scene.cameraProperty(CameraProperty.X) + ":" + scene.cameraProperty(CameraProperty.Y))
    textSprite.setPosition(scene.cameraProperty(CameraProperty.X) + 0, scene.cameraProperty(CameraProperty.Bottom) - 8)
})
